services:
  blog:
    build: ./
    container_name: blog-app
    restart: always
    labels:
      - "traefik.enable=true"

      # --- ROUTER DEFINITION ---
      - "traefik.http.routers.blog.rule=Host(`theodoroferreira.dev`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.routers.blog.tls.certresolver=letsencrypt"

      # --- SERVICE DEFINITION ---
      - "traefik.http.services.blog.loadbalancer.server.port=8090"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
