services:
  blog:
    build: ./
    container_name: blog-app
    restart: always
    labels:
      - "traefik.enable=true"

      # --- ROUTER DEFINITION ---
      - "traefik.http.routers.bot.rule=Host(`theodoroferreira.dev`) && PathPrefix(`/api`)"
      - "traefik.http.routers.bot.entrypoints=websecure"
      - "traefik.http.routers.bot.tls=true"
      - "traefik.http.routers.bot.tls.certresolver=letsencrypt"

      # --- SERVICE DEFINITION ---
      - "traefik.http.services.bot.loadbalancer.server.port=8090"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
