entryPoints:
  web:
    address: ":90"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: theogferreira@outlook.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
